config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  get 'home/about' => 'homes#about'

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
##
##
## connecting with a user using user_id.
##
##

class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true, length: {minimum: 1, maximum: 20}
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
##
##
## we need image for profile.
## connecting with books using id.
##
##

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  validate

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_up_path_for(resource)
      user_path(resource)
    end

    def after_sign_in_path_for(resource)
      user_path(current_user)
    end

    def after_sign_out_path_for(resource)
      root_path
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    comment=BookComment.find(params[:id])
    comment.destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :correct_user, only: [:edit, :update]

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:newbook] = "You have created book successfully."
      redirect_to book_path(@new_book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @new_book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @id = @book.user_id
    @user = User.find(@id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:editbook] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    redirect_to(books_path) unless  @book.user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def index
    @user= current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:updateuser] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_info.html.erb
<div class="new_book mt-3">
  <h2>New book</h2>

  <%= form_with model: Book.new do |newbook| %>
    <div>
      <p>Title</p>
      <%= newbook.text_field :title, class: "w-100 form-control" %>
    </div>

    <div>
      <p>Opinion</p>
      <%= newbook.text_field :body, class: "w-100 form-control" %>
    </div>

    <div>
      <%= newbook.submit "Create Book", class: "mt-2 btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/books/_user_info.html.erb
<div class="user_info">
  <h2>User info</h2>

  <%= image_tag @user.get_profile_image(100, 100) %>
  
  <table class="table">
    <tbody>
      <tr><th>name</th><th><%= @user.name %></th></tr>
      <tr><th>introduction</th><th><%= @user.introduction %></th></tr>
    </tbody>
  </table>

  <div class="edit_botton">
    <%= link_to edit_user_path(@user), method: :get, class: "btn btn-outline-secondary mx-auto btn-block" do %>
      <i class = "fas fa-user-cog" ></i>
    <% end %>
  </div>
  
</div>

app/views/books/edit.html.erb
<div class="container">
  <class="row">
    <!--edit book-->
    <div class="offset-md-4 col-md-4 offset-md-4 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with model: @book do |book| %>

        <!--error message-->
        <div class="error_message">
          <% if @book.errors.any? %>
            <%= @book.errors.count %> error prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <p>Title</p>
        <%= book.text_field :title, class:"form-control mb-4" %>

        <p>Opinion</p>
        <%= book.text_field :body, class:"form-control mb-4" %>

        <div><%= book.submit "Update Book", class:"mb-4 btn btn-success" %></div>
      <% end %>

      <%= link_to 'Show', book_path(@book) %> | <%= link_to 'Back', books_path %>
    </div>

  </div>
</div>

app/views/books/index.html.erb
<div class="container px-2">
  <div class="row">

    <!--user information-->
    <div class="col-md-3">
      <%= render 'user_info' %>

      <!--error message-->
      <div class="error_message">
        <% if @new_book.errors.any? %>
          <%= @new_book.errors.count %> error prohibited this obj from being saved:
          <ul>
            <% @new_book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <%= render 'book_info' %>
    </div>

    <!--all books-->
    <div class="offset-md-1 col-md-8">
      <h2>Books</h2>

      <table class="table  table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(80, 80)), user_path(book.user), :controller => 'books', :action => 'show'%>
              </td>
              <td><%= link_to book.title , book_path(book.id), :controller => 'books', :action => 'show' %></td>
              <td><%= book.body %></td>
              <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete, class: "text-danger" do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post,  class: "text-primary" do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count%>
                <% end %>
              <% end %>
              </td>
              <td>コメント数：<%= book.book_comments.count%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container px-2">
  <div class="row">

    <!--user information-->
    <div class="col-md-3">
      <%= render 'user_info' %>
      <%= render 'book_info' %>
    </div>

    <!--user book detail-->
    <div class="offset-md-1 col-md-8 px-md-5">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_profile_image(100,100) %><br>
              <%= link_to @book.user.name, user_path(@book.user) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete, class: "text-danger" do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post,  class: "text-primary" do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>

            <% if @book.user==current_user %>
              <td><%= link_to edit_book_path(@book.id), method: :get, class: 'btn btn-success' do %>Edit<% end %></td>
              <td><%= link_to book_path(@book.id), method: :delete, class: 'btn btn-danger', data: { confirm: "本当に消しますか？" } do %>Destroy<% end %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <table>
        <tbody>

          <% @book.book_comments.each do |comment|%>
          <tr>
            <td><%= image_tag comment.user.get_profile_image(50,50) %><br>
                <%= link_to comment.user.name, user_path(comment.user) %>
            </td>
            <td><%= comment.comment %></td>
            <% if comment.user==current_user %>
             <td><%= link_to "Destroy", book_book_comment_path(comment.book, comment), method: :delete, class: "btn btn-danger" %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= form_with model: [@book, @book_comment] do |comment| %>
        <%= comment.text_area :comment, class: "form-control" %>
        <%= comment.submit "送信" %>
      <% end %>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="main_title">
  <h1>
    Welcome to <i class="fas fa-book">Bookers</i>!
  </h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3"></div>

    <!--contains-->
    <div class="top col-md-6">
      <div class="top_title">
        <h1>welcome to <i class="fas fa-book"></i><span class="font-weight-bold">Bookers</span> !!</h1>
      </div>

      <div class="main_text">
        <p class="mb-3">In <i class="fa-solid fa-book"></i><span class="font-weight-bold">Bookers</span>,</p>
        <p class="mb-3">you can share and exchange your opinion, inipressions, and emotions</p>
        <p class="mb-3">about various books!</p>
      </div>

      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block d-block mx-auto mb-3 col-10" %>
      <%= link_to "Sign up", new_user_registration_path,  class: "btn btn-success btn-block d-block mx-auto mb-3 col-10" %>
    </div>

    <div class="col-md-3"></div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cd22d97277.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100 vw-100">

  　<!--header(navigation bar)-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <!--logo-->
          <a class="navbar-brand" href="/">Bookers</a>

          <!--navigation bar-->
          <!--navigation bar (hamberger icon)-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--navigation bar (open <=> close)-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to user_path(current_user), class: 'nav-link text-light' do %><i class="fas fa-home"></i> Home <% end %></li>
                <li class="nav-item"><%= link_to users_path, class: 'nav-link text-light' do %><i class="fas fa-users"></i> Users <% end %></li>
                <li class="nav-item"><%= link_to books_path, class: 'nav-link text-light' do %><i class="fas fa-book-open"></i> Books <% end %></li>
                <li class="nav-item"><%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %><i class="fas fa-sign-out-alt"></i> Logout <% end %></li>
              <% else %>
                <li class="nav-item"><%= link_to root_path, class: 'nav-link text-light' do %><i class="fas fa-home"></i> Home<% end %></li>
                <li class="nav-item"><%= link_to home_about_path, class: 'nav-link text-light' do %><i class="fas fa-link"></i> About<% end %></li>
                <li class="nav-item"><%= link_to new_user_registration_path, class: 'nav-link text-light' do %><i class="fas fa-user-plus"></i> sign up<% end %></li>
                <li class="nav-item"><%= link_to user_session_path, class: 'nav-link text-light' do %><i class="fas fa-sign-in-alt"></i> Login<% end %></li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <!--main-->
    <%= flash[:notice] %>
    <%= flash[:updateuser] %>
    <%= flash[:newbook] %>
    <%= flash[:editbook] %>

    <main class="mt-3 px-5">
      <%= yield %>
    </main>

　　<!--footer-->
    <footer class="mt-5 mx-auto">
      <div class="container">
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<!--error message-->
<div class="error_message">
  <% if @user.errors.any? %>
    <%= @user.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<!--user edit-->
<div class="container px-2">
  <div class="row">
    <div class="offset-md-4 col-md-4 offset-md-4">
      <h1>User info</h1>

      <%= form_with model: @user do |user| %>
        <p>Name</p>
        <%= user.text_field :name, autofocus: true %>

        <p>Image</p>
        <%= user.file_field :profile_image, accept: "image/*" %>

        <P>Introduction</p>
        <%= user.text_field :introduction %>

        <%= user.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-2">
  <div class="row">

    <!--user information-->
    <div class="user_info col-md-3">
      <%= render 'books/user_info' %>
      <%= render 'books/book_info' %>
    </div>

    <!--all books-->
    <div class="offset-md-1 col-md-8 px-md-5">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80, 80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-2">
  <div class="row">

    <!--user information-->
    <div class="col-md-3">
      <%= render 'books/user_info' %>
      <%= render 'books/book_info' %>
    </div>

    <!--user book-->
    <div class="offset-md-1 col-md-8">
      <h2>Books</h2>

      <table class="table  table-hover">
        <thead>
          <tr><th></th><th>Title</th><th>Opinion</th><th></th><th></th></tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %><%= image_tag book.user.get_profile_image(80,80) %><% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete, class: "text-danger" do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post,  class: "text-primary" do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count%>
                <% end %>
              <% end %>
              </td>
              <td>コメント数：<%= book.book_comments.count%></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>